/**
 *  @file
 *  @brief   Functionality for populating a pplme::engine::PplRepository from
 *           a CSV file generated by generate_pplme_dataset.py.
 *  @author  j.ho
 */
#ifndef PPLME_LIBPPLMEENGINE_PPLSLURPER_H_
#define PPLME_LIBPPLMEENGINE_PPLSLURPER_H_


#include <string>


namespace pplme {
namespace engine {
class PplRepository;
}  // engine
}  // pplme


namespace pplme {
namespace engine {


/**
 *  Expected format of the CSV file is as follows:
 *  <id>,<name>,<dob>,<latitude>,<longitude>
 *  e.g.:
 *  ce5a75db-c399-4e7c-9e18-e06cfe6974d8,Ardis Bergen,1961-11-22,71.8616001097,-94.8030884371
 */
class PplSlurper {
 public:
  /**
   *  @remarks  Only stores the filename.  To get the good stuff, Slurp().
   */
  explicit PplSlurper(std::string const& ppl_data_csv_file);

  /**
   *  @return true iff the file was fully parsed.
   */
  bool Populate(PplRepository* ppl_repo);
  
 private:
  std::string const ppl_data_csv_file_;
};


}  // namespace engine
}  // namespace pplme


#endif  // PPLME_LIBPPLMEENGINE_PPLSLURPER_H_
